evo_config:
  _target_: rayevolve.core.EvolutionConfig
  patch_types:
    - "diff"
    - "full"
    - "cross"
  patch_type_probs:
    - 0.45
    - 0.45
    - 0.1
  num_generations: 300
  max_parallel_jobs: 5
  max_patch_resamples: 3
  max_patch_attempts: 3
  meta_rec_interval: 10 
  meta_max_recommendations: 5
  embedding_model: "text-embedding-3-small"
  max_novelty_attempts: 3 
  code_embed_sim_threshold: 0.95
  llm_models:
    - "gemini-2.5-flash"
  llm_kwargs:
    temperatures: # this doesn't work for reasoning models temp is fixed at 0
      - 0.0
      - 0.5
      - 1.0
    max_tokens: 16384
  meta_llm_models:
    - "gemini-2.5-flash"
  novelty_llm_models:    
    - "gemini-2.5-flash"
  results_dir: ${output_dir}

