evo_config:
  _target_: rayevolve.core.EvolutionConfig
  patch_types:
    - "diff"
    - "full"
    - "cross"
  patch_type_probs:
    - 0.6
    - 0.3
    - 0.1
  num_generations: 100
  max_parallel_jobs: 10
  max_patch_resamples: 3
  max_patch_attempts: 3
  llm_models:
    - "gemini-2.5-pro"
    - "gemini-2.5-flash"
    - "gpt-4.1-mini"
    - "gpt-4.1-nano"
    - "bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0"
    - "o4-mini"
  llm_dynamic_selection: ucb
  llm_kwargs:
    temperatures:
      - 0.0
      - 0.5
      - 1.0
    max_tokens: 16384
  meta_rec_interval: 10
  meta_llm_models:
    - "gpt-4.1"
  meta_llm_kwargs:
    temperatures:
      - 0.0
  embedding_model: "text-embedding-3-small"
  results_dir: ${output_dir}
  