evo_config:
  _target_: rayevolve.core.EvolutionConfig
  patch_types:
    - "diff"
    - "full"
    - "cross"
  patch_type_probs:
    - 0.6
    - 0.3
    - 0.1
  num_generations: 8
  max_parallel_jobs: 1
  max_patch_attempts: 2
  llm_models:
    - "gemini-2.5-flash"
  llm_dynamic_selection: null
  #embedding_model: "gemini-embedding-exp-03-07"
  embedding_model: "text-embedding-3-small"
  results_dir: ${output_dir}



