evo_config:
  _target_: rayevolve.core.EvolutionConfig
  patch_types:
    - "diff"
    - "full"
  patch_type_probs:
    - 0.5
    - 0.5
  num_generations: 8
  max_parallel_jobs: 1
  max_patch_attempts: 2
  llm_models:
    - "gemini-2.5-flash"
  llm_dynamic_selection: null
  embedding_model: "gemini-embedding-exp-03-07"
  results_dir: ${output_dir}



