# from circle packing example TODO: update
db_config:
  _target_: rayevolve.database.DatabaseConfig
  db_path: "evolution_db.sqlite"
  num_islands: 5
  archive_size: 40
  # inspiration parameters
  elite_selection_ratio: 0.3
  num_archive_inspirations: 4
  num_top_k_inspirations: 2
  # island migration parameters
  migration_interval: 10
  migration_rate: 0.1
  island_elitism: true
  # parent selection parameters
  parent_selection_strategy: "weighted"
  # power-law parent selection parameters
  exploitation_alpha: 1.0
  exploitation_ratio: 0.2
  # weighted tree parent selection parameters
  parent_selection_lambda: 10.0