# from mad example TODO: update
db_config:
  _target_: rayevolve.database.DatabaseConfig
  db_path: "evolution_db.sqlite"
  num_islands: 2
  archive_size: 40
  exploitation_ratio: 0.2
  elite_selection_ratio: 0.3
  num_archive_inspirations: 4
  num_top_k_inspirations: 2
  migration_interval: 10
  migration_rate: 0.0
  island_elitism: true
  parent_selection_strategy: "weighted"
  parent_selection_lambda: 10.0