evaluate_function:
  _target_: examples.agent_design.evaluate.main
  program_path: ???
  results_dir: ???

distributed_job_config:
  _target_: rayevolve.launch.SlurmCondaJobConfig
  modules:
  - "cuda/12.4"
  - "cudnn/8.9.7"
  - "hpcx/2.20"
  eval_program_path: "rayevolve/eval_hydra.py"
  conda_env: "rayevolve"
  time: "01:00:00"
  cpus: 16
  gpus: 1
  mem: "8G"

evo_config:
  task_sys_msg: >
    You are an expert machine learning engineer tasked with designing a new agentic system capable of solving math problems.

    You will be given a program that implements an agent scaffold. Your goal is to design a new agentic system by suggesting improvements to the scaffold.

    You will be given a set of performance metrics for the program. Your goal is to maximize the `combined_score` of the program.
  language: "python"
  init_program_path: "examples/agent_design/initial.py"
  job_type: "slurm_conda"

exp_name: "rayevolve_agent_design"
